package com.gadministrativa.controller;

import com.gadministrativa.security.dto.LoginRequest;
import com.gadministrativa.security.dto.RegisterRequest;
import com.gadministrativa.security.entity.User;
import com.gadministrativa.security.service.JwtService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import com.gadministrativa.security.service.UserRegisterService;

import java.util.Map;

@RestController
@RequestMapping("/auth")
@RequiredArgsConstructor
public class AuthController {

    private final AuthenticationManager authenticationManager;
    private final JwtService jwtService;
    private final UserRegisterService userRegisterService;

    /**
     * Registers a new user in DB.
     * @param registerRequest Body of the request received.
     * @return 201CREATED or 500 if any exception is thrown.
     */
    @PostMapping("/register")
    public ResponseEntity<?> register(@RequestBody RegisterRequest registerRequest) {
        try {
            User user = userRegisterService.registerUser(registerRequest);

            return ResponseEntity.status(HttpStatus.CREATED).body(user);
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", "Error interno"));
        }
    }

    /**
     * Receives the login request body and pass it to the authentication manager verifying it.
     * Then returns the token with a 200OK response.
     * @param loginRequest The received request with user credentials.
     * @return Response with the JWT token.
     */
    @PostMapping("/login")
    public ResponseEntity<?> login(@RequestBody LoginRequest loginRequest) {
        try {
            Authentication auth = authenticationManager.authenticate(
                    new UsernamePasswordAuthenticationToken(
                            loginRequest.getEmail(),
                            loginRequest.getPassword()
                    )
            ); // auth is now a token generated by the AuthenticationManager after verifying user credentials.

            String token = jwtService.generateToken(loginRequest.getEmail()); // Generate the token based on the email.

            // Returns the token formatted as a response.
            return ResponseEntity.ok(Map.of(
                    "token", token,
                    "type", "Bearer"
            ));

        } catch (BadCredentialsException e) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                    .body("Invalid credentials"); // In case of invalid credentials.
        }
    }
}