// AuthController.java - VERSIÓN CORRECTA
package com.gadministrativa.controller;  // ← DEBE estar en controller

import com.gadministrativa.security.dto.LoginRequest;
import com.gadministrativa.security.service.JwtService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController
@RequestMapping("/auth")
public class AuthController {

    @Autowired
    private AuthenticationManager authenticationManager;

    @Autowired
    private JwtService jwtService;

    /**
     * Receives the login request body and pass it to the authentication manager verifying it.
     * Then returns the token with a 200OK response.
     * @param loginRequest The received request with user credentials.
     * @return Response with the JWT token.
     */
    @PostMapping("/login")
    public ResponseEntity<?> login(@RequestBody LoginRequest loginRequest) {
        try {
            Authentication auth = authenticationManager.authenticate(
                    new UsernamePasswordAuthenticationToken(
                            loginRequest.getEmail(),
                            loginRequest.getPassword()
                    )
            ); // auth is now a token generated by the AuthenticationManager after verifying user credentials.

            String token = jwtService.generateToken(loginRequest.getEmail()); // Generate the token based on the email.

            // Returns the token formatted as a response.
            return ResponseEntity.ok(Map.of(
                    "token", token,
                    "type", "Bearer"
            ));

        } catch (BadCredentialsException e) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                    .body("Invalid credentials"); // In case of invalid credentials.
        }
    }
}